/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorldEventSchema =
  | AgentSpawnedEvent
  | AgentStateChangedEvent
  | AgentRemovedEvent
  | ConnectionChangedEvent
  | SnapshotReplacedEvent
  | ConversationUserAddedEvent
  | ConversationDeltaEvent
  | ConversationCompletedEvent
  | ApprovalRequestedEvent
  | ApprovalResolvedEvent
  | RunFinishedEvent;
export type SchemaVersion = 1;
export type EventId = string;
export type Sequence = number;
export type OccurredAt = string;
export type Source = string;
export type Evidence = "verified" | "inferred";
export type Type = "agent.spawned";
export type AgentId = string;
export type Kind = "yume" | "scheduled" | "delegated";
export type DisplayName = string;
export type Status =
  | "idle"
  | "entering"
  | "thinking"
  | "moving"
  | "working"
  | "waiting_approval"
  | "completed"
  | "failed"
  | "exiting"
  | "stale";
export type Room = "ceo" | "memory" | "research" | "work" | "automation" | "lobby";
export type TaskSummary = string | null;
export type StartedAt = string | null;
export type NextRunAt = string | null;
export type SchemaVersion1 = 1;
export type EventId1 = string;
export type Sequence1 = number;
export type OccurredAt1 = string;
export type Source1 = string;
export type Evidence1 = "verified" | "inferred";
export type Type1 = "agent.state_changed";
export type AgentId1 = string;
export type Status1 =
  | "idle"
  | "entering"
  | "thinking"
  | "moving"
  | "working"
  | "waiting_approval"
  | "completed"
  | "failed"
  | "exiting"
  | "stale";
export type Room1 = "ceo" | "memory" | "research" | "work" | "automation" | "lobby";
export type TaskSummary1 = string | null;
export type NextRunAt1 = string | null;
export type SchemaVersion2 = 1;
export type EventId2 = string;
export type Sequence2 = number;
export type OccurredAt2 = string;
export type Source2 = string;
export type Evidence2 = "verified" | "inferred";
export type Type2 = "agent.removed";
export type AgentId2 = string;
export type SchemaVersion3 = 1;
export type EventId3 = string;
export type Sequence3 = number;
export type OccurredAt3 = string;
export type Source3 = string;
export type Evidence3 = "verified" | "inferred";
export type Type3 = "connection.changed";
export type Status2 = "starting" | "connected" | "degraded" | "disconnected";
export type Reason = string | null;
export type SchemaVersion4 = 1;
export type EventId4 = string;
export type Sequence4 = number;
export type OccurredAt4 = string;
export type Source4 = string;
export type Evidence4 = "verified" | "inferred";
export type Type4 = "snapshot.replaced";
export type Sequence5 = number;
export type Connection = "starting" | "connected" | "degraded" | "disconnected";
export type TelemetryMode = "standard" | "enhanced";
export type SessionId = string | null;
export type AgentId3 = string;
export type Kind1 = "yume" | "scheduled" | "delegated";
export type DisplayName1 = string;
export type Status3 =
  | "idle"
  | "entering"
  | "thinking"
  | "moving"
  | "working"
  | "waiting_approval"
  | "completed"
  | "failed"
  | "exiting"
  | "stale";
export type Room2 = "ceo" | "memory" | "research" | "work" | "automation" | "lobby";
export type Evidence5 = "verified" | "inferred";
export type TaskSummary2 = string | null;
export type StartedAt1 = string | null;
export type NextRunAt2 = string | null;
export type Agents = AgentView[];
export type MessageId = string;
export type Role = "user" | "assistant";
export type Text = string;
export type Conversation = ConversationMessage[];
export type SchemaVersion5 = 1;
export type EventId5 = string;
export type Sequence6 = number;
export type OccurredAt5 = string;
export type Source5 = string;
export type Evidence6 = "verified" | "inferred";
export type Type5 = "conversation.user_added";
export type Text1 = string;
export type MessageId1 = string;
export type SchemaVersion6 = 1;
export type EventId6 = string;
export type Sequence7 = number;
export type OccurredAt6 = string;
export type Source6 = string;
export type Evidence7 = "verified" | "inferred";
export type Type6 = "conversation.delta";
export type SchemaVersion7 = 1;
export type EventId7 = string;
export type Sequence8 = number;
export type OccurredAt7 = string;
export type Source7 = string;
export type Evidence8 = "verified" | "inferred";
export type Type7 = "conversation.completed";
export type SchemaVersion8 = 1;
export type EventId8 = string;
export type Sequence9 = number;
export type OccurredAt8 = string;
export type Source8 = string;
export type Evidence9 = "verified" | "inferred";
export type Type8 = "approval.requested";
export type AgentId4 = string;
export type RunId = string;
export type ApprovalId = string;
export type Prompt = string;
export type SchemaVersion9 = 1;
export type EventId9 = string;
export type Sequence10 = number;
export type OccurredAt9 = string;
export type Source9 = string;
export type Evidence10 = "verified" | "inferred";
export type Type9 = "approval.resolved";
export type AgentId5 = string;
export type SchemaVersion10 = 1;
export type EventId10 = string;
export type Sequence11 = number;
export type OccurredAt10 = string;
export type Source10 = string;
export type Evidence11 = "verified" | "inferred";
export type Type10 = "run.finished";
export type RunId1 = string;
export type Outcome = "completed" | "failed" | "cancelled";
export type Error = string | null;

export interface AgentSpawnedEvent {
  schema_version?: SchemaVersion;
  event_id: EventId;
  sequence: Sequence;
  occurred_at: OccurredAt;
  source: Source;
  evidence: Evidence;
  type: Type;
  agent_id: AgentId;
  payload: AgentSpawnedPayload;
  [k: string]: unknown;
}
export interface AgentSpawnedPayload {
  kind: Kind;
  display_name: DisplayName;
  status: Status;
  room: Room;
  task_summary?: TaskSummary;
  started_at?: StartedAt;
  next_run_at?: NextRunAt;
  [k: string]: unknown;
}
export interface AgentStateChangedEvent {
  schema_version?: SchemaVersion1;
  event_id: EventId1;
  sequence: Sequence1;
  occurred_at: OccurredAt1;
  source: Source1;
  evidence: Evidence1;
  type: Type1;
  agent_id: AgentId1;
  payload: AgentStatePayload;
  [k: string]: unknown;
}
export interface AgentStatePayload {
  status: Status1;
  room: Room1;
  task_summary?: TaskSummary1;
  next_run_at?: NextRunAt1;
  [k: string]: unknown;
}
export interface AgentRemovedEvent {
  schema_version?: SchemaVersion2;
  event_id: EventId2;
  sequence: Sequence2;
  occurred_at: OccurredAt2;
  source: Source2;
  evidence: Evidence2;
  type: Type2;
  agent_id: AgentId2;
  payload?: Payload;
  [k: string]: unknown;
}
export interface Payload {
  [k: string]: string;
}
export interface ConnectionChangedEvent {
  schema_version?: SchemaVersion3;
  event_id: EventId3;
  sequence: Sequence3;
  occurred_at: OccurredAt3;
  source: Source3;
  evidence: Evidence3;
  type: Type3;
  payload: ConnectionPayload;
  [k: string]: unknown;
}
export interface ConnectionPayload {
  status: Status2;
  reason?: Reason;
  [k: string]: unknown;
}
export interface SnapshotReplacedEvent {
  schema_version?: SchemaVersion4;
  event_id: EventId4;
  sequence: Sequence4;
  occurred_at: OccurredAt4;
  source: Source4;
  evidence: Evidence4;
  type: Type4;
  payload: SnapshotPayload;
  [k: string]: unknown;
}
export interface SnapshotPayload {
  snapshot: WorldSnapshot;
  [k: string]: unknown;
}
export interface WorldSnapshot {
  sequence: Sequence5;
  connection: Connection;
  telemetry_mode?: TelemetryMode;
  session_id?: SessionId;
  agents: Agents;
  conversation?: Conversation;
  [k: string]: unknown;
}
export interface AgentView {
  agent_id: AgentId3;
  kind: Kind1;
  display_name: DisplayName1;
  status: Status3;
  room: Room2;
  evidence: Evidence5;
  task_summary?: TaskSummary2;
  started_at?: StartedAt1;
  next_run_at?: NextRunAt2;
  [k: string]: unknown;
}
export interface ConversationMessage {
  message_id: MessageId;
  role: Role;
  text: Text;
  [k: string]: unknown;
}
export interface ConversationUserAddedEvent {
  schema_version?: SchemaVersion5;
  event_id: EventId5;
  sequence: Sequence6;
  occurred_at: OccurredAt5;
  source: Source5;
  evidence: Evidence6;
  type: Type5;
  payload: ConversationPayload;
  [k: string]: unknown;
}
export interface ConversationPayload {
  text: Text1;
  message_id: MessageId1;
  [k: string]: unknown;
}
export interface ConversationDeltaEvent {
  schema_version?: SchemaVersion6;
  event_id: EventId6;
  sequence: Sequence7;
  occurred_at: OccurredAt6;
  source: Source6;
  evidence: Evidence7;
  type: Type6;
  payload: ConversationPayload;
  [k: string]: unknown;
}
export interface ConversationCompletedEvent {
  schema_version?: SchemaVersion7;
  event_id: EventId7;
  sequence: Sequence8;
  occurred_at: OccurredAt7;
  source: Source7;
  evidence: Evidence8;
  type: Type7;
  payload: ConversationPayload;
  [k: string]: unknown;
}
export interface ApprovalRequestedEvent {
  schema_version?: SchemaVersion8;
  event_id: EventId8;
  sequence: Sequence9;
  occurred_at: OccurredAt8;
  source: Source8;
  evidence: Evidence9;
  type: Type8;
  agent_id: AgentId4;
  payload: ApprovalPayload;
  [k: string]: unknown;
}
export interface ApprovalPayload {
  run_id: RunId;
  approval_id: ApprovalId;
  prompt: Prompt;
  [k: string]: unknown;
}
export interface ApprovalResolvedEvent {
  schema_version?: SchemaVersion9;
  event_id: EventId9;
  sequence: Sequence10;
  occurred_at: OccurredAt9;
  source: Source9;
  evidence: Evidence10;
  type: Type9;
  agent_id: AgentId5;
  payload: Payload1;
  [k: string]: unknown;
}
export interface Payload1 {
  [k: string]: string;
}
export interface RunFinishedEvent {
  schema_version?: SchemaVersion10;
  event_id: EventId10;
  sequence: Sequence11;
  occurred_at: OccurredAt10;
  source: Source10;
  evidence: Evidence11;
  type: Type10;
  payload: RunFinishedPayload;
  [k: string]: unknown;
}
export interface RunFinishedPayload {
  run_id: RunId1;
  outcome: Outcome;
  error?: Error;
  [k: string]: unknown;
}
